### ISSUE TITLE
"Management only" attribute not correctly set

### ISSUE THREAD

**Issue by Azmodeszer** [NetTech2001/netbox-interface-synchronization#2]
The plugin does not sync the "management only" flag with the proper value even if it is set to true in the device type interface template.

**Comment by NetTech2001** [comment]
Interesting idea. The plugin was only designed to correct the names and interface type but I like the idea of any value in the new template being included. I will look into this for a future release.

**Comment by NetTech2001** [comment]
This has been fixed in release 4.0.3
