### ISSUE TITLE
exclude_virtual_interfaces does not work

### ISSUE THREAD

**Issue by PaulR282** [NetTech2001/netbox-interface-synchronization#5]
I have a virtual VLAN interface (with `mgmt_only`) that shows up in the comparison. It is already present in the device and the device type. I didn't change the plugin config, so `exclude_virtual_interfaces` should be, by default, `true`. If I click `add` and apply the changes, I get an error because the Interface already exists.

**Comment by NetTech2001** [comment]
If you set the interface type to Virtual it should be excluded, the Management only checkbox doesn't define the interface as virtual.
