### ISSUE TITLE
Anyone having problems with Netbox 4.0.7?

### ISSUE THREAD

**Issue by newsonesnsd** [NetTech2001/netbox-interface-synchronization#7]
Hi, I try to use with netbox 4.0.7 but when I restart netbox. It will be 502 Bad Gateway
Has anyone tried it?
PS. Before I install this plugins. I just update python to 3.12 and also upgraded venv.

**Comment by NetTech2001** [comment]
I am running it on version 4.0.8 and it seems to be working just fine

**Comment by newsonesnsd** [comment]
Thanks, But I try on my test netbox server and my production. I have the same result (return 502 Bad gateway) after I restart netbox
![image](https://github.com/user-attachments/assets/bb56efa0-b38d-4325-a0fb-b40f317363f3)

**Comment by newsonesnsd** [comment]
Do you have any suggestions?
![image](https://github.com/user-attachments/assets/774028c3-5630-4b16-8df7-da6c5ef4634f)

Or after I update python. Is there anything else to do?

**Comment by newsonesnsd** [comment]
I got it, I just try to remove venv and install new venv to make sure that use python 3.12
After I check my venv after upgrade venv It still use python 3.10
