### ISSUE TITLE
Not kompatible with python3.10

### ISSUE THREAD

**Issue by maxzapp** [NetTech2001/netbox-interface-synchronization#8]
Hi i run netbox v4.0.5 ON ubuntu 22.04.4 LTS with python 3.10. If i try to install i got the following error message:

"Ignored the following versions that require a different python version 4.0.0 Requires Python >=3.11 "
same message for4.0.1 4.0.3

As netbox supports python 3.10 i would expect plugins should work as well.

i tried to install python 3.11 in parallel but if i symlink python3 to python3.11 netbox doesn't work anymore.

Any advice
Thx

**Comment by bradmoutoux** [comment]
I run python 3.12 and what I found is if you install python 3.12 or 3.11, do not try and symlink.  Just use python3.12 instead of python3 in your scripting and when you run the upgrade.sh using python3.12 it will create a new venv under python3.12 and all will work just fine.

**Comment by bradmoutoux** [comment]
I am now on 4.1.2 and python 3.12 and it works well.

Sincerely,

Brad Moutoux
Sr. Systems Engineer
1045 S John Rodes Blvd | Melbourne, FL 32904
Office: 321-473-0327 | Mobile: 321-468-8166
***@***.***<https://www.nextechna.com/>

**Comment by maxzapp** [comment]
Hi,

now i changed to this value PYTHON="${PYTHON:-python3.12}"
and this line  echo "  sudo PYTHON=/usr/bin/python3.12 ./upgrade.sh"
the script runs sucessfully but if i try to install the plugin i ran into these results. I added also the version of python and pip in the snippet.

tom@netboxneo:/opt/netbox$ source /opt/netbox/venv/bin/activate
(venv) tom@netboxneo:/opt/netbox$ pip install netbox-interface-synchronization
Collecting netbox-interface-synchronization
  Downloading netbox_interface_synchronization-4.0.3-py3-none-any.whl.metadata (2.1 kB)
Downloading netbox_interface_synchronization-4.0.3-py3-none-any.whl (21 kB)
Installing collected packages: netbox-interface-synchronization
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/opt/netbox-4.0.10/venv/lib/python3.12/site-packages/netbox_interface_synchronization'
Check the permissions.

(venv) tom@netboxneo:/opt/netbox$ sudo pip install netbox-interface-synchronization
ERROR: Ignored the following versions that require a different python version: 4.0.0 Requires-Python >=3.11; 4.0.1 Requires-Python >=3.11; 4.0.3 Requires-Python >=3.11
ERROR: Could not find a version that satisfies the requirement netbox-interface-synchronization (from versions: none)
ERROR: No matching distribution found for netbox-interface-synchronization
(venv) tom@netboxneo:/opt/netbox$ python -V
Python 3.12.7
(venv) tom@netboxneo:/opt/netbox$ pip -V
pip 24.2 from /opt/netbox-4.0.10/venv/lib/python3.12/site-packages/pip (python 3.12)
(venv) tom@netboxneo:/opt/netbox$ deacivate
deacivate: command not found
(venv) tom@netboxneo:/opt/netbox$ deactivate
tom@netboxneo:/opt/netbox$ python -V
Python 3.12.7
tom@netboxneo:/opt/netbox$


sorry but i still have problems to install this very helpfull (i used the old one a lot) plugin.

BR

**Comment by bradmoutoux** [comment]
One thing I found.  Comment out all of your plugins.  Do the upgrade.  Then go back and uncomment them out 2 at a time and restart the Netbox service.  Check to see if it still runs after each set of plugins you uncomment.  Once you have the ones that won’t work, leave them commented out.  The run migrations and whatever else you need.  Then even if you run the upgrade.sh that will just rebuild the environment, it should work just fine.  Mine did.  But that was how I had to upgrade.  A lot seems to have to deal with Django and some new unique label requirements.  But after the upgrade, enabling the plugin seems to work correctly with Django.

Kind of all over the place, but hope that helps.

Sincerely,

Brad Moutoux
Sr. Systems Engineer
1045 S John Rodes Blvd | Melbourne, FL 32904
Office: 321-473-0327 | Mobile: 321-468-8166
***@***.***<https://www.nextechna.com/>
